url: https://donniewest.com/MattSite
baseurl: ""

# Site settings
title: Matt Hargrave Realty
email: matt@matthargrave.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ef0005
  secondary: 0061c2
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/matt.hargrave.sold.it/
  - title: google-plus
    url: https://plus.google.com/u/0/b/115066171609944608218/115066171609944608218
  - title: instagram
    url: https://www.instagram.com/hargraverealtyprofessionals/
  - title: linkedin
    url: https://www.linkedin.com/profile/preview?locale=en_US&trk=prof-0-sb-preview-primary-button
  - title: youtube
    url: https://www.youtube.com/channel/UCdbZyBXIYB564_ur1YZqh_w/feed

# Postal address (add as many lines as necessary)
address:
  - line: 1900 NW S Outer Road
  - line: Blue Springs MO 64015

# Build settings
markdown: kramdown
permalink: pretty
